Add a readme to welcome people in our repo
codeforosnabrueck/codeforosnabrueck.github.io pull request #23
Opened 2019-09-17 19:01 UTC by wagnerpeer

Fix #20

Mostly taken from the website itself.

2020-10-19 19:14 UTC, jhinghaus requested changes

2020-10-19 19:14 UTC, jhinghaus commented on Readme.md
> +* https://www.meetup.com/CodeForOsnabrueck
Meetup sollten wir besser nicht mehr mit auflisten.

2020-10-20 20:33 UTC, wagnerpeer commented on Readme.md
> +* https://www.meetup.com/CodeForOsnabrueck
Link ist entfernt. Leider funktioniert gettogether.community nicht verlaesslich. Dafuer habe ich aber noch die codefor.de website mit dazu gepackt.

2020-10-21 19:36 UTC, jhinghaus approved these changes

2020-10-21 20:00 UTC, merged